[Feat] 도서 검색 목록 조회 API / 책 상세정보 조회 API
BookwooriAlpineClub/Bookwoori-Back pull request #24
Opened 2024-10-25 16:17 UTC by minseoooooo

## 🛠️ 구현 기능
  - 도서 검색 목록 조회 API 구현
  - 책 상세정보 조회 API 구현
  - 스프링시큐리티 기본 로그인 화면 제거

## 📝 구현 방법
  - swagger이나 postman 테스트시 unauthorized 에러 발생 (제 로컬에서만 생기는 문제일수도 있어요)
  - CoreApplication run시 자동으로 생기는 스프링시큐리티 기본 로그인화면이 원인인 것으로 확인
  - `(exclude = SecurityAutoConfiguration.class)` 코드 추가 후 에러 해결 

## 🔥 구현 결과
[
![스크린샷 2024-10-26 01 09 44](https://github.com/user-attachments/assets/7dd0f44b-3837-4881-a05f-8d37641004e3)
![스크린샷 2024-10-26 01 10 04](https://github.com/user-attachments/assets/5ebdde07-22e9-4906-9701-61463c5235e7)
](url)
## 🎯 Resolve
  - #19, #22, #23

2024-10-26 08:38 UTC, crHwang0822 requested changes

2024-10-26 08:38 UTC, crHwang0822 commented on core/src/main/java/org/bookwoori/core/CoreApplication.java
> +@SpringBootApplication(exclude = SecurityAutoConfiguration.class)
❗  이 부분 삭제하고 SecurityConfig 클래스 97 line 을
`.anyRequest().permitAll())` 로 한번 수정해봐주시겠어요 ???

2024-10-26 08:38 UTC, crHwang0822 commented on core/src/main/java/org/bookwoori/core/domain/book/service/BookService.java
> +  private static final String TTB_KEY = "ttboesnimnos1216001"; // 알라딘 API Key
❗ yml 이랑 @Value 어노테이션 사용해서 값 감춰주세용

2024-10-26 08:38 UTC, crHwang0822 commented on core/src/main/java/org/bookwoori/core/domain/book/service/BookService.java
> +  public List<BookResponseDto> findBooksByKeyword(String keyword) { // 도서 검색
❗ Service 단에서 조회 담당 메소드는 find~ 가 아닌 get~으로 통일해주시묜 감사하겠습니당

2024-10-26 08:38 UTC, crHwang0822 commented on core/src/main/java/org/bookwoori/core/domain/book/service/BookService.java
> +              isbn13, cover);
💊 50-57 line : BookResponseDto에 JsonNode 타입을 매개변수로 받는 from 메소드 생성해서 처리하는 편이 코드가 더 깔끔하지 않을ㄲㅏ요?!

2024-10-26 08:38 UTC, crHwang0822 commented on core/src/main/java/org/bookwoori/core/domain/book/service/BookService.java
> +        return new BookDetailResponseDto(title, author, publisher, pubDate, itemPage, description,
💊 line 83 - 91 : 여기도 마찬가지로 from 메소드 사용하면 좋을 것 같아용

2024-10-26 13:42 UTC, gkdudans approved these changes

2024-10-26 13:42 UTC, gkdudans commented on core/src/main/java/org/bookwoori/core/domain/book/controller/BookController.java
> +  @GetMapping
💬Swagger @Operation 어노테이션 활용하는 부분 추가하면 좋을 거 같습니닷

2024-10-26 13:42 UTC, gkdudans commented on core/src/main/java/org/bookwoori/core/domain/book/service/BookService.java
> +  private ObjectMapper objectMapper;
💊 이미 @RequiredArgsConstructor를 사용하고 있으니 private final로 바꾸는 건 어떨까요?

2024-10-26 13:42 UTC, gkdudans commented on core/src/main/java/org/bookwoori/core/domain/book/service/BookService.java
> +      e.printStackTrace();
💊 Custom Exception 사용해서 에러처리하는 건 어떨까욤

2024-10-28 11:44 UTC, minseoooooo commented on core/src/main/java/org/bookwoori/core/domain/book/controller/BookController.java
> +  public List<BookResponseDto> getBookList(@RequestParam String keyword) { // 도서 검색
리턴값 -> 타입 와일드카드로 통일하는걸로

2024-10-30 05:22 UTC, merged