Feat/record
BookwooriAlpineClub/Bookwoori-Back pull request #64
Opened 2024-11-12 13:22 UTC by minseoooooo

## 🛠️ 구현 기능
  - Record 추가 / 수정 / 삭제 API 
  - 진행도별 책 목록 조회 API
  - 내 감상평 목록 조회 API

## 📝 구현 방법

## 🔥 구현 결과

## 🎯 Resolve
  - #57 
  - #58 
  - #59 
  - #60 
  - #61

2024-11-13 11:52 UTC, gkdudans requested changes
❓책 기록 상세정보 조회 API(책 개별 독서 현황 혹은 감상평 조회)는 원래 존재하지 않는 건가요? 책 상세정보 조회만 존재하는 거 같아서 질문해 봅니당

2024-11-13 11:52 UTC, gkdudans commented on core/src/main/java/org/bookwoori/core/domain/record/dto/request/RecordRequestDto.java
> +    Integer star,
❓Integer를 사용하는 특별한 이유가 있을까요? 없다면 int로 통일해 주세요
💊 ReadinStatus에서 빈 문자열을 검사할 필요는 없기 때문에 `@NotBlank` 보다는 `@NotNull`이 관례적으로 더 적합할 것 같아요

2024-11-13 11:52 UTC, gkdudans commented on core/src/main/java/org/bookwoori/core/domain/record/facade/RecordFacade.java
> +
❓Record 추가할 때 review가 반드시 추가되는 개념인가욤? 다 읽은 책에만 review를 추가할 수 있는 거 아닌가요?

2024-11-13 11:52 UTC, gkdudans commented on core/src/main/java/org/bookwoori/core/domain/record/facade/RecordFacade.java
> +    }
❗위에 남긴 코멘트대로 Record와 Review의 Create/Update API  분리하는 게 좋을 거 같습니다

2024-11-13 11:52 UTC, gkdudans commented on core/src/main/java/org/bookwoori/core/domain/record/facade/RecordFacade.java
> +@Log4j2
💊 `@Transactional`을 class 단위에 붙이고, `@Transactional(readOnly = true)`를 필요한 메서드에 붙이면 더 좋을 거 같습니다

2024-11-13 11:52 UTC, gkdudans commented on core/src/main/java/org/bookwoori/core/domain/record/facade/RecordFacade.java
> +    @Transactional
❗ `@Transactional(readOnly = true)`로 수정해 주세요 + getRecordsByStatus에도 동일한 어노테이션 추가해 주세요

2024-11-13 11:52 UTC, gkdudans commented on core/src/main/java/org/bookwoori/core/domain/record/facade/RecordFacade.java
> +    public List<RecordResponseDto> getRecordsByStatus(ReadingStatus status) {
💊 필수는 아니긴 하지만, List<ResponseDto>로 반환하는 게 아닌 새로운 ResponseDto에 List를 필드로 넣는 방식으로 통일하기로 했어서 이 부분도 그렇게 수정하면 좋을 거 같아요!
💊 map을 사용해서 조금 더 간결하게 리팩토링할 수도 있을 거 같습니다 (아래 코드는 예시)
```
    List<RecordResponseDto> recordResponseDtos = recordService.getRecordsByStatus(status).stream()
            .map(RecordResponseDto::from)
            .toList();
    return new RecordListResponseDto(recordResponseDtos);
}
```

2024-11-13 11:52 UTC, gkdudans commented on core/src/main/java/org/bookwoori/core/domain/record/dto/response/RecordResponseDto.java
> +    String review,
❗review 필드 사용하지 않으면 삭제해 주세요!

2024-11-15 16:35 UTC, minseoooooo commented
> ❓책 기록 상세정보 조회 API(책 개별 독서 현황 혹은 감상평 조회)는 원래 존재하지 않는 건가요? 책 상세정보 조회만 존재하는 거 같아서 질문해 봅니당

넵 원래 작성했던 API 명세서 기준으로 구현한 상태이긴 합니다.

2024-11-15 16:38 UTC, merged