[Feat] 알림 관련 기능 구현
BookwooriAlpineClub/Bookwoori-Back pull request #82
Opened 2024-11-23 15:27 UTC by minseoooooo

## 🛠️ 구현 기능
  - 기기 등록 / 삭제 / 조회 API (DeviceController)
  - 디엠 알림 / 채널생성 알림 / 리뷰이모지 알림 / 채팅채널 알림 API (NotificationController)

## 🎯 Resolve
  - #66 
  - #80 
  - #81

2024-11-24 03:06 UTC, crHwang0822 reviewed
👍 수고하셨습니다~! 코멘트 남겼는데 확인 후 답멘 부탁드립니다!

2024-11-24 03:06 UTC, crhwang822 commented on notification/src/main/java/org/bookwoori/notification/config/MongoConfig.java
> +        System.out.println(connection);
💊 디버깅 코드 삭제해주세요!

2024-11-24 03:06 UTC, crhwang822 commented on notification/src/main/java/org/bookwoori/notification/config/RedisConfig.java
> +
❗ 비밀번호 설정 추가해주세요!

2024-11-24 03:06 UTC, crhwang822 commented on notification/src/main/java/org/bookwoori/notification/controller/DeviceController.java
> +        log.info("GET /notification-server/device/{}", userId);
💊 디버깅 코드 삭제해주세요!

2024-11-24 03:06 UTC, crhwang822 commented on notification/src/main/java/org/bookwoori/notification/controller/DeviceController.java
> +        log.info("POST /notification-server/device");
💊 디버깅 코드 삭제해주세요!

2024-11-24 03:06 UTC, crhwang822 commented on notification/src/main/java/org/bookwoori/notification/controller/DeviceController.java
> +        log.info("DELETE /notification-server/device/{}", userId);
💊 디버깅 코드 삭제해주세요!

2024-11-24 03:06 UTC, crhwang822 commented on notification/src/main/java/org/bookwoori/notification/controller/NotificationController.java
> +        log.info("POST /notification-server/direct / {}", request.getTarget());
💊 디버깅 코드 삭제해주세요!

2024-11-24 03:06 UTC, crhwang822 commented on notification/src/main/java/org/bookwoori/notification/controller/NotificationController.java
> +        log.info("POST /notification-server/channel / {}", request.getTarget());
💊 디버깅 코드 삭제해주세요!

2024-11-24 03:06 UTC, crhwang822 commented on notification/src/main/java/org/bookwoori/notification/controller/NotificationController.java
> +        log.info("POST /notification-server/emoji / {}", request.getTarget());
💊 디버깅 코드 삭제해주세요!

2024-11-24 03:06 UTC, crhwang822 commented on notification/src/main/java/org/bookwoori/notification/controller/NotificationController.java
> +        log.info("POST /notification-server/chat / {}", request.getTarget());
💊 디버깅 코드 삭제해주세요!

2024-11-24 03:06 UTC, crhwang822 commented on notification/src/main/java/org/bookwoori/notification/dto/request/ChannelMessageRequest.java
> +    private Long userId;
💊 저희 도메인명이 Member라 memberId로 통일하는 게 좋을 것 같습니다~!

2024-11-24 03:06 UTC, crhwang822 commented on notification/src/main/java/org/bookwoori/notification/dto/request/ChannelMessageRequest.java
> +    private String username;
💊 Member 도메인 nickname 필드를 뜻하는 거라면 nickname 으로 변경해주세요!

2024-11-24 03:06 UTC, crhwang822 commented on notification/src/main/java/org/bookwoori/notification/dto/response/DeviceResponse.java
> +    public static DeviceResponse fromEntity(Device device) {
💊 메소드명 from 으로 통일해주세요 ~!

2024-11-24 03:06 UTC, crHwang0822 commented on notification/src/main/java/org/bookwoori/notification/exception/CustomExceptionStatus.java
> +    SUCCESS(true, 1000, "요청에 성공하였습니다."),
💊 line 10 ~ line 13 : 이 부분 core 서버 에러 코드 고려해서 번호를 통일시키거나 아예 숫자 범위를 다르게 작성하는 게 좋을 것 같습니다

2024-11-24 03:06 UTC, crHwang0822 commented on notification/src/main/java/org/bookwoori/notification/dto/request/EmojiMessageRequest.java
> +
💊 여기 공백 삭제해주세요!

2024-11-24 03:06 UTC, crHwang0822 commented on notification/src/main/java/org/bookwoori/notification/util/MessageType.java
> +public class MessageType {
❓ 혹시 이 클래스는 어디에 쓰이나요? (`DirectChatRequest`, `ChannelChatRequest` DTO의 `type` 필드는 STRING 타입이라 여쭤봅니다.) 그리고 CHAT 서버의 `MessageType` ENUM이랑 내용을 통일시켜야 하지는 않나요?!

2024-11-24 15:38 UTC, gkdudans requested changes

2024-11-24 15:38 UTC, gkdudans commented on notification/src/main/java/org/bookwoori/notification/controller/DeviceController.java
> +@RequestMapping("/notification-server/device")
💊 통일성을 위해 /notification-server -> /notification으로 변경하는 거 어떨까요?
💊 device -> devices 복수형으로 변경해도 좋을 거 같습니다

2024-11-24 15:38 UTC, gkdudans commented on notification/src/main/java/org/bookwoori/notification/controller/DeviceController.java
> +    public DataResponse<DeviceResponse> getDevice(@PathVariable("id") Long userId) {
❓ResponseEntity<?>와 ResponseEntity 가 아닌 ResponseService를 따로 생성해서 만드는 이유가 있는 건가요?

2024-11-24 15:38 UTC, gkdudans commented on notification/src/main/java/org/bookwoori/notification/dto/request/ChatMessageRequest.java
> +public class ChatMessageRequest {
❗record 타입으로 수정해 주세요 (다른 dto들도 마찬가지)
❗Dto 전부 ~Dto로 끝나도록 이름 수정해 주세욤

2024-11-24 15:38 UTC, gkdudans commented on notification/src/main/java/org/bookwoori/notification/dto/response/DeviceResponse.java
> +        return response;
❗setter 사용하지 않고 `builder().build()` 사용하는 코드로 변경해 주세요

2024-11-24 15:38 UTC, gkdudans commented on notification/src/main/java/org/bookwoori/notification/exception/ExceptionAdvice.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
❓ExceptionAdvice는 예외 처리를 위한 GlobalExceptionHandler 역할을 하는 거 맞나요? 목적이 같다면 Core 서버 및 다른 서버에서 사용하고 있는 공통된 ErrorDto 및 GlobalExceptionHandler를 사용하면 좋을 거 같습니닷

2024-11-24 15:38 UTC, gkdudans commented on notification/src/main/java/org/bookwoori/notification/service/DeviceService.java
> +    }
❓Device 엔티티의 register 생성 메서드를 통해 생성해야 하는 특별한 이유가 있나요? requestDto에서 toEntity 및 builder 이용해서 생성하고 save해도 되지 않나욤

2024-11-24 15:38 UTC, gkdudans commented on notification/src/main/java/org/bookwoori/notification/service/DeviceService.java
> +    }
❓마찬가지로 Device 엔티티에 delete() 메서드를 둬야 할 이유가 있을까요? Repository에서 delete하면 되지 않나요?

2024-11-27 04:02 UTC, crHwang0822 approved these changes

2024-11-28 03:36 UTC, minseoooooo commented on notification/src/main/java/org/bookwoori/notification/util/MessageType.java
> +public class MessageType {
Fcmutil에서, 메시지 타입별로 알림 다르게 생성하는 용도로 사용되구, MessageType ENUM과 통일되게 수정했습니다!

2024-11-28 03:40 UTC, gkdudans approved these changes
💬 나중에 시간이 된다면 이전에 리뷰드린 대로 Core 서버와 통일성 있는 구현으로 리팩토링하면 좋을 거 같습니닷

2024-11-29 07:16 UTC, merged